name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: |
          pipenv install
      - name: Lint with flake8
        run: |
          pipenv run lint
      - name: Test with pytest
        run: |
          pipenv run tests
      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
      - name: Build Wheel
        run: |
          pipenv run build
      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: rbldap-wheel-${{ matrix.python-version }}
          path: rbldap-1.0.0.dev0-py3-none-any.whl
