name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
      - name: Lint with flake8
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run lint
      - name: Test with pytest
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run tests
      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: tests/results/
      - name: Build Wheel
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run build
      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: rbldap-wheel
          path: dist/rbldap-1.0.0.dev0-py3-none-any.whl
